// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("AltLanDS.PushSharp")]
[assembly: AssemblyCompanyAttribute("AltLanDS")]
[assembly: AssemblyCopyrightAttribute("Copyright © AltLanDS 2012-2016")]
[assembly: AssemblyVersionAttribute("4.0.10.1")]
[assembly: AssemblyFileVersionAttribute("4.0.10.2.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "4.0.10.1";
        internal const string InformationalVersion = "4.0.10.1";
    }
}
